In [1]:
import pandas as pd
import time
import datetime
import geopy
import scipy
infile = pd.read_excel('../data/AviationSafety.xlsx')
#showcols(infile)
df = infile.drop(infile.columns[[i for i in range(33,45)]],axis = 1, inplace = False)

In [2]:
def showcols(dataframe,lazyprinting = False):
    '''
    :param dataframe:
    :return nothing, but print out the dataframe column and corresponding indexes instead.
    The dataframe is not iterable through external package imports,
    so it must be defined within the jupyter kernel.
    '''
    if lazyprinting:
        print(dataframe.columns)
    for i in enumerate(dataframe.columns):
        print (i)

def get_occupants(inseam:str):
    '''

    :param inseam:
    Specifies the input of the function, which is defined as Fatalities:int Occupants:int
    :return:
    (fatalaties:int,occupants:int)
    '''
    if True:
        try:
            inseam = inseam.split('/')
            inseam = [i.split(':') for i in inseam]
            result = list()
            #print(inseam)
            for i in inseam:
                left_candidate = i[0].strip().lstrip()
                right_candidate = 0 if i[1].strip().rstrip().lstrip()== '' else int(i[1].strip().rstrip().lstrip())
                result.append([left_candidate,right_candidate])#Normalise the empty entry to 0
        except Exception:
            print('inseam is :' + str(inseam))
            print('i is : '+ str(i))
            pass
        finally:
            return (result[0][1],result[1][1])
assert(get_occupants('Fatalities: 0 / Occupants: 2')==(0,2))
assert(get_occupants('Fatalities: 0 / Occupants: '))

In [3]:
dxx = df.drop(df[df['Crash site elevation:'].isnull()].index)
i = dxx['Crash site elevation:'].values
k = []
for c in i:
    try:
        if c == '-':
            pass
        print(c)
        k.append(c.split()[0])
    except:
        k.append(c)
    

k

1506 m (4941 feet) amsl
1506 m (4941 feet) amsl
3048 m (10000 feet) amsl
1450 m (4757 feet) amsl
4084 m (13399 feet) amsl
2000 m (6562 feet) amsl
2 m (7 feet) amsl
615 m (2018 feet) amsl
213 m (699 feet) amsl
1189 m (3901 feet) amsl
975 m (3199 feet) amsl
1355 m (4446 feet) amsl
523 m (1716 feet) amsl
1310 m (4298 feet) amsl
131 m (430 feet) amsl
251 m (823 feet) amsl
3505 m (11499 feet) amsl
2438 m (7999 feet) amsl
Royal Army Service Corps. L/Cpl (T/14531630) M Adcock -
354 m (1161 feet) amsl
189 m (620 feet) amsl
7 m (23 feet) amsl
434 m (1424 feet) amsl
4600 m (15092 feet) amsl
503 m (1650 feet) amsl
1610 m (5282 feet) amsl
853 m (2799 feet) amsl
285 m (935 feet) amsl
900 m (2953 feet) amsl
4572 m (15000 feet) amsl
340 m (1115 feet) amsl
2591 m (8501 feet) amsl
178 m (584 feet) amsl
36 m (118 feet) amsl
211 m (692 feet) amsl
710 m (2329 feet) amsl
2187 m (7175 feet) amsl
30 m (98 feet) amsl
-3 m (-10 feet) amsl
2870 m (9416 feet) amsl
2438 m (7999 feet) amsl
2590 m (8497 feet) amsl
1700 m (5577 feet) amsl
215 m (705 feet) amsl
4633 m (15200 feet) amsl
3527 m (11572 feet) amsl
115 m (377 feet) amsl
1750 m (5741 feet) amsl
1890 m (6201 feet) amsl
2043 m (6703 feet) amsl
13 m (43 feet) amsl
5 m (16 feet) amsl
850 m (2789 feet) amsl
445 m (1460 feet) amsl
73 m (240 feet) amsl
9 m (30 feet) amsl
2800 m (9186 feet) amsl
350 m (1148 feet) amsl
25 m (82 feet) amsl
1067 m (3501 feet) amsl
2752 m (9029 feet) amsl
14 m (46 feet) amsl
233 m (764 feet) amsl
3414 m (11201 feet) amsl
1829 m (6001 feet) amsl
802 m (2631 feet) amsl
3500 m (11483 feet) amsl
1432 m (4698 feet) amsl
30 m (98 feet) amsl
488 m (1601 feet) amsl
1328 m (4357 feet) amsl
421 m (1381 feet) amsl
4267 m (13999 feet) amsl
89 m (292 feet) amsl
427 m (1401 feet) amsl
4160 m (13648 feet) amsl
1098 m (3602 feet) amsl
610 m (2001 feet) amsl
41 m (135 feet) amsl
975 m (3199 feet) amsl
280 m (919 feet) amsl
192 m (630 feet) amsl
2285 m (7497 feet) amsl
167 m (548 feet) amsl
559 m (1834 feet) amsl
2600 m (8530 feet) amsl
610 m (2001 feet) amsl
148 m (486 feet) amsl
550 m (1804 feet) amsl
1950 m (6398 feet) amsl
681 m (2234 feet) amsl
3658 m (12001 feet) amsl
2200 m (7218 feet) amsl
351 m (1152 feet) amsl
841 m (2759 feet) amsl
203 m (666 feet) amsl
2049 m (6722 feet) amsl
4750 m (15584 feet) amsl
3768 m (12362 feet) amsl
1320 m (4331 feet) amsl
808 m (2651 feet) amsl
294 m (965 feet) amsl
1099 m (3606 feet) amsl
44 m (144 feet) amsl
11 m (36 feet) amsl
377 m (1237 feet) amsl
1167 m (3829 feet) amsl
420 m (1378 feet) amsl
1322 m (4337 feet) amsl
1160 m (3806 feet) amsl
1280 m (4199 feet) amsl
267 m (876 feet) amsl
3109 m (10200 feet) amsl
160 m (525 feet) amsl
508 m (1667 feet) amsl
5280 m (17323 feet) amsl
1200 m (3937 feet) amsl
262 m (860 feet) amsl
1270 m (4167 feet) amsl
11 m (36 feet) amsl
73 m (240 feet) amsl
287 m (942 feet) amsl
682 m (2238 feet) amsl
67 m (220 feet) amsl
1036 m (3399 feet) amsl
1687 m (5535 feet) amsl
104 m (341 feet) amsl
2548 m (8360 feet) amsl
3587 m (11768 feet) amsl
202 m (663 feet) amsl
78 m (256 feet) amsl
681 m (2234 feet) amsl
1200 m (3937 feet) amsl
680 m (2231 feet) amsl
3150 m (10335 feet) amsl
1152 m (3780 feet) amsl
42 m (138 feet) amsl
1020 m (3346 feet) amsl
1500 m (4921 feet) amsl
10 m (33 feet) amsl
5 m (16 feet) amsl
702 m (2303 feet) amsl
1158 m (3799 feet) amsl
2100 m (6890 feet) amsl
452 m (1483 feet) amsl
754 m (2474 feet) amsl
1585 m (5200 feet) amsl
385 m (1263 feet) amsl
3800 m (12467 feet) amsl
488 m (1601 feet) amsl
610 m (2001 feet) amsl
9 m (30 feet) amsl
3124 m (10249 feet) amsl
442 m (1450 feet) amsl
192 m (630 feet) amsl
632 m (2073 feet) amsl
1219 m (3999 feet) amsl
476 m (1562 feet) amsl
306 m (1004 feet) amsl
1755 m (5758 feet) amsl
393 m (1289 feet) amsl
950 m (3117 feet) amsl
6 m (20 feet) amsl
617 m (2024 feet) amsl
6 m (20 feet) amsl
179 m (587 feet) amsl
701 m (2300 feet) amsl
34 m (112 feet) amsl
1860 m (6102 feet) amsl
1208 m (3963 feet) amsl
762 m (2500 feet) amsl
83 m (272 feet) amsl
509 m (1670 feet) amsl
1327 m (4354 feet) amsl
494 m (1621 feet) amsl
1700 m (5577 feet) amsl
15 m (49 feet) amsl
4 m (13 feet) amsl
4 m (13 feet) amsl
27 m (89 feet) amsl
750 m (2461 feet) amsl
11 m (36 feet) amsl
1130 m (3707 feet) amsl
11 m (36 feet) amsl
46 m (151 feet) amsl
20 m (66 feet) amsl
632 m (2073 feet) amsl
632 m (2073 feet) amsl
2195 m (7201 feet) amsl
34 m (112 feet) amsl
1995 m (6545 feet) amsl
48 m (157 feet) amsl
939 m (3081 feet) amsl
632 m (2073 feet) amsl
52 m (171 feet) amsl
187 m (614 feet) amsl
46 m (151 feet) amsl
6 m (20 feet) amsl
531 m (1742 feet) amsl
74 m (243 feet) amsl
5500 m (18045 feet) amsl
204 m (669 feet) amsl
610 m (2001 feet) amsl
9 m (30 feet) amsl
374 m (1227 feet) amsl
5000 m (16404 feet) amsl
366 m (1201 feet) amsl
1951 m (6401 feet) amsl
610 m (2001 feet) amsl
21 m (69 feet) amsl
915 m (3002 feet) amsl
447 m (1467 feet) amsl
3400 m (11155 feet) amsl
6 m (20 feet) amsl
1662 m (5453 feet) amsl
51 m (167 feet) amsl
625 m (2051 feet) amsl
84 m (276 feet) amsl
18 m (59 feet) amsl
2896 m (9501 feet) amsl
807 m (2648 feet) amsl
160 m (525 feet) amsl
860 m (2822 feet) amsl
1300 m (4265 feet) amsl
1365 m (4478 feet) amsl
350 m (1148 feet) amsl
6 m (20 feet) amsl
2199 m (7215 feet) amsl
3 m (10 feet) amsl
762 m (2500 feet) amsl
11 m (36 feet) amsl
376 m (1234 feet) amsl
147 m (482 feet) amsl
1905 m (6250 feet) amsl
5 m (16 feet) amsl
7 m (23 feet) amsl
463 m (1519 feet) amsl
1365 m (4478 feet) amsl
155 m (509 feet) amsl
2300 m (7546 feet) amsl
400 m (1312 feet) amsl
397 m (1302 feet) amsl
4 m (13 feet) amsl
95 m (312 feet) amsl
594 m (1949 feet) amsl
157 m (515 feet) amsl
287 m (942 feet) amsl
5974 m (19600 feet) amsl
3505 m (11499 feet) amsl
1023 m (3356 feet) amsl
244 m (801 feet) amsl
561 m (1841 feet) amsl
183 m (600 feet) amsl
185 m (607 feet) amsl
1530 m (5020 feet) amsl
78 m (256 feet) amsl
732 m (2402 feet) amsl
258 m (846 feet) amsl
1067 m (3501 feet) amsl
37 m (121 feet) amsl
2743 m (8999 feet) amsl
240 m (787 feet) amsl
119 m (390 feet) amsl
1524 m (5000 feet) amsl
211 m (692 feet) amsl
228 m (748 feet) amsl
343 m (1125 feet) amsl
2000 m (6562 feet) amsl
2438 m (7999 feet) amsl
19 m (62 feet) amsl
10 m (33 feet) amsl
1 m (3 feet) amsl
1265 m (4150 feet) amsl
26 m (85 feet) amsl
298 m (978 feet) amsl
299 m (981 feet) amsl
14 m (46 feet) amsl
320 m (1050 feet) amsl
1993 m (6539 feet) amsl
132 m (433 feet) amsl
2226 m (7303 feet) amsl
171 m (561 feet) amsl
921 m (3022 feet) amsl
2808 m (9213 feet) amsl
95 m (312 feet) amsl
57 m (187 feet) amsl
468 m (1535 feet) amsl
185 m (607 feet) amsl
155 m (509 feet) amsl
547 m (1795 feet) amsl
180 m (591 feet) amsl
413 m (1355 feet) amsl
185 m (607 feet) amsl
1260 m (4134 feet) amsl
48 m (157 feet) amsl
625 m (2051 feet) amsl
335 m (1099 feet) amsl
7 m (23 feet) amsl
7 m (23 feet) amsl
43 m (141 feet) amsl
217 m (712 feet) amsl
2014 m (6608 feet) amsl
183 m (600 feet) amsl
1288 m (4226 feet) amsl
1463 m (4800 feet) amsl
183 m (600 feet) amsl
2 m (7 feet) amsl
2200 m (7218 feet) amsl
4335 m (14222 feet) amsl
313 m (1027 feet) amsl
80 m (262 feet) amsl
1524 m (5000 feet) amsl
10 m (33 feet) amsl
99 m (325 feet) amsl
30 m (98 feet) amsl
238 m (781 feet) amsl
5430 m (17815 feet) amsl
9 m (30 feet) amsl
506 m (1660 feet) amsl
3500 m (11483 feet) amsl
99 m (325 feet) amsl
763 m (2503 feet) amsl
38 m (125 feet) amsl
38 m (125 feet) amsl
1220 m (4003 feet) amsl
2100 m (6890 feet) amsl
241 m (791 feet) amsl
3021 m (9911 feet) amsl
4 m (13 feet) amsl
1006 m (3301 feet) amsl
1768 m (5801 feet) amsl
374 m (1227 feet) amsl
695 m (2280 feet) amsl
799 m (2621 feet) amsl
7 m (23 feet) amsl
192 m (630 feet) amsl
495 m (1624 feet) amsl
3087 m (10128 feet) amsl
4 m (13 feet) amsl
3505 m (11499 feet) amsl
15 m (49 feet) amsl
237 m (778 feet) amsl
2225 m (7300 feet) amsl
1554 m (5098 feet) amsl
346 m (1135 feet) amsl
550 m (1804 feet) amsl
326 m (1070 feet) amsl
238 m (781 feet) amsl
3749 m (12300 feet) amsl
92 m (302 feet) amsl
3 m (10 feet) amsl
244 m (801 feet) amsl
5 m (16 feet) amsl
540 m (1772 feet) amsl
1494 m (4902 feet) amsl
732 m (2402 feet) amsl
237 m (778 feet) amsl
-3 m (-10 feet) amsl
1200 m (3937 feet) amsl
152 m (499 feet) amsl
228 m (748 feet) amsl
8 m (26 feet) amsl
1377 m (4518 feet) amsl
457 m (1499 feet) amsl
313 m (1027 feet) amsl
1851 m (6073 feet) amsl
686 m (2251 feet) amsl
1800 m (5906 feet) amsl
4420 m (14501 feet) amsl
1463 m (4800 feet) amsl
65 m (213 feet) amsl
2 m (7 feet) amsl
1533 m (5030 feet) amsl
2712 m (8898 feet) amsl
724 m (2375 feet) amsl
430 m (1411 feet) amsl
2443 m (8015 feet) amsl
23 m (75 feet) amsl
907 m (2976 feet) amsl
150 m (492 feet) amsl
197 m (646 feet) amsl
234 m (768 feet) amsl
2178 m (7146 feet) amsl
701 m (2300 feet) amsl
1325 m (4347 feet) amsl
5 m (16 feet) amsl
201 m (659 feet) amsl
2 m (7 feet) amsl
132 m (433 feet) amsl
12 m (39 feet) amsl
500 m (1640 feet) amsl
900 m (2953 feet) amsl
3030 m (9941 feet) amsl
228 m (748 feet) amsl
1006 m (3301 feet) amsl
1886 m (6188 feet) amsl
382 m (1253 feet) amsl
33 m (108 feet) amsl
632 m (2073 feet) amsl
143 m (469 feet) amsl
2559 m (8396 feet) amsl
3054 m (10020 feet) amsl
82 m (269 feet) amsl
2321 m (7615 feet) amsl
5547 m (18199 feet) amsl
2813 m (9229 feet) amsl
270 m (886 feet) amsl
90 m (295 feet) amsl
2469 m (8100 feet) amsl
80 m (262 feet) amsl
2301 m (7549 feet) amsl
5 m (16 feet) amsl
1400 m (4593 feet) amsl
762 m (2500 feet) amsl
237 m (778 feet) amsl
152 m (499 feet) amsl
396 m (1299 feet) amsl
1890 m (6201 feet) amsl
1450 m (4757 feet) amsl
320 m (1050 feet) amsl
406 m (1332 feet) amsl
1336 m (4383 feet) amsl
248 m (814 feet) amsl
2406 m (7894 feet) amsl
393 m (1289 feet) amsl
108 m (354 feet) amsl
26 m (85 feet) amsl
367 m (1204 feet) amsl
515 m (1690 feet) amsl
1158 m (3799 feet) amsl
4481 m (14701 feet) amsl
2773 m (9098 feet) amsl
2938 m (9639 feet) amsl
25 m (82 feet) amsl
192 m (630 feet) amsl
298 m (978 feet) amsl
625 m (2051 feet) amsl
228 m (748 feet) amsl
1377 m (4518 feet) amsl
1716 m (5630 feet) amsl
1402 m (4600 feet) amsl
1189 m (3901 feet) amsl
4877 m (16001 feet) amsl
1030 m (3379 feet) amsl
1830 m (6004 feet) amsl
104 m (341 feet) amsl
6 m (20 feet) amsl
1059 m (3474 feet) amsl
2767 m (9078 feet) amsl
2560 m (8399 feet) amsl
756 m (2480 feet) amsl
701 m (2300 feet) amsl
731 m (2398 feet) amsl
809 m (2654 feet) amsl
3368 m (11050 feet) amsl
1189 m (3901 feet) amsl
173 m (568 feet) amsl
35 m (115 feet) amsl
2120 m (6955 feet) amsl
27 m (89 feet) amsl
11 m (36 feet) amsl
585 m (1919 feet) amsl
494 m (1621 feet) amsl
298 m (978 feet) amsl
49 m (161 feet) amsl
342 m (1122 feet) amsl
209 m (686 feet) amsl
107 m (351 feet) amsl
238 m (781 feet) amsl
500 m (1640 feet) amsl
567 m (1860 feet) amsl
33 m (108 feet) amsl
802 m (2631 feet) amsl
4 m (13 feet) amsl
1814 m (5951 feet) amsl
207 m (679 feet) amsl
1551 m (5089 feet) amsl
25 m (82 feet) amsl
3610 m (11844 feet) amsl
384 m (1260 feet) amsl
681 m (2234 feet) amsl
1208 m (3963 feet) amsl
843 m (2766 feet) amsl
865 m (2838 feet) amsl
4100 m (13451 feet) amsl
1550 m (5085 feet) amsl
975 m (3199 feet) amsl
122 m (400 feet) amsl
1551 m (5089 feet) amsl
384 m (1260 feet) amsl
17 m (56 feet) amsl
349 m (1145 feet) amsl
610 m (2001 feet) amsl
3993 m (13100 feet) amsl
3048 m (10000 feet) amsl
153 m (502 feet) amsl
72 m (236 feet) amsl
1493 m (4898 feet) amsl
2859 m (9380 feet) amsl
1200 m (3937 feet) amsl
1655 m (5430 feet) amsl
2767 m (9078 feet) amsl
1000 m (3281 feet) amsl
1707 m (5600 feet) amsl
2941 m (9649 feet) amsl
43 m (141 feet) amsl
2926 m (9600 feet) amsl
2834 m (9298 feet) amsl
1760 m (5774 feet) amsl
1687 m (5535 feet) amsl
4 m (13 feet) amsl
17003
3 m (10 feet) amsl
997 m (3271 feet) amsl
31 m (102 feet) amsl
80 m (262 feet) amsl
4100 m (13451 feet) amsl
103 m (338 feet) amsl
625 m (2051 feet) amsl
246 m (807 feet) amsl
275 m (902 feet) amsl
6 m (20 feet) amsl
2743 m (8999 feet) amsl
8 m (26 feet) amsl
179 m (587 feet) amsl
61 m (200 feet) amsl
945 m (3100 feet) amsl
753 m (2470 feet) amsl
153 m (502 feet) amsl
1650 m (5413 feet) amsl
18 m (59 feet) amsl
313 m (1027 feet) amsl
4 m (13 feet) amsl
293 m (961 feet) amsl
432 m (1417 feet) amsl
29 m (95 feet) amsl
121 m (397 feet) amsl
2774 m (9101 feet) amsl
1703 m (5587 feet) amsl
1541 m (5056 feet) amsl
892 m (2927 feet) amsl
2014 m (6608 feet) amsl
685 m (2247 feet) amsl
373 m (1224 feet) amsl
1860 m (6102 feet) amsl
62 m (203 feet) amsl
424 m (1391 feet) amsl
911 m (2989 feet) amsl
2916 m (9567 feet) amsl
320 m (1050 feet) amsl
19 m (62 feet) amsl
192 m (630 feet) amsl
1707 m (5600 feet) amsl
1274 m (4180 feet) amsl
34 m (112 feet) amsl
209 m (686 feet) amsl
3960 m (12992 feet) amsl
241 m (791 feet) amsl
610 m (2001 feet) amsl
1492 m (4895 feet) amsl
4 m (13 feet) amsl
34 m (112 feet) amsl
142 m (466 feet) amsl
41 m (135 feet) amsl
126 m (413 feet) amsl
2384 m (7822 feet) amsl
2192 m (7192 feet) amsl
1981 m (6499 feet) amsl
41 m (135 feet) amsl
488 m (1601 feet) amsl
900 m (2953 feet) amsl
488 m (1601 feet) amsl
2530 m (8301 feet) amsl
2357 m (7733 feet) amsl
2064 m (6772 feet) amsl
1890 m (6201 feet) amsl
722 m (2369 feet) amsl
3347 m (10981 feet) amsl
760 m (2493 feet) amsl
9707
700 m (2297 feet) amsl
-
1036 m (3399 feet) amsl
3962 m (12999 feet) amsl
2600 m (8530 feet) amsl
1750 m (5741 feet) amsl
36628
2160 m (7087 feet) amsl
912 m (2992 feet) amsl
400 m (1312 feet) amsl
2682 m (8799 feet) amsl
2900 m (9514 feet) amsl
3980 m (13058 feet) amsl
2286 m (7500 feet) amsl
3901 m (12799 feet) amsl
3645 m (11959 feet) amsl
2540 m (8333 feet) amsl
3660 m (12008 feet) amsl
4115 m (13501 feet) amsl
1048 m (3438 feet) amsl
668 m (2192 feet) amsl

['1506',
 '1506',
 '3048',
 '1450',
 '4084',
 '2000',
 '2',
 '615',
 '213',
 '1189',
 '975',
 '1355',
 '523',
 '1310',
 '131',
 '251',
 '3505',
 '2438',
 'Royal',
 '354',
 '189',
 '7',
 '434',
 '4600',
 '503',
 '1610',
 '853',
 '285',
 '900',
 '4572',
 '340',
 '2591',
 '178',
 '36',
 '211',
 '710',
 '2187',
 '30',
 '-3',
 '2870',
 '2438',
 '2590',
 '1700',
 '215',
 '4633',
 '3527',
 '115',
 '1750',
 '1890',
 '2043',
 '13',
 '5',
 '850',
 '445',
 '73',
 '9',
 '2800',
 '350',
 '25',
 '1067',
 '2752',
 '14',
 '233',
 '3414',
 '1829',
 '802',
 '3500',
 '1432',
 '30',
 '488',
 '1328',
 '421',
 '4267',
 '89',
 '427',
 '4160',
 '1098',
 '610',
 '41',
 '975',
 '280',
 '192',
 '2285',
 '167',
 '559',
 '2600',
 '610',
 '148',
 '550',
 '1950',
 '681',
 '3658',
 '2200',
 '351',
 '841',
 '203',
 '2049',
 '4750',
 '3768',
 '1320',
 '808',
 '294',
 '1099',
 '44',
 '11',
 '377',
 '1167',
 '420',
 '1322',
 '1160',
 '1280',
 '267',
 '3109',
 '160',
 '508',
 '5280',
 '1200',
 '262',
 '1270',
 '11',
 '73',
 '287',
 '682',
 '67',
 '1036',
 '1687',
 '104',
 '2548',
 '3587',
 '202',
 '78',
 '681',
 '1200',
 '680',
 '3150',
 '1152',
 '42',
 '1020',
 '1500',
 '10',
 '5',
 '702',
 '1158',
 '2100',
 '452',
 '754',
 '1585',
 '385',
 '3800',
 '488',
 '610',
 '9',
 '3124',
 '442',
 '192',
 '632',
 '1219',
 '476',
 '306',
 '1755',
 '393',
 '950',
 '6',
 '617',
 '6',
 '179',
 '701',
 '34',
 '1860',
 '1208',
 '762',
 '83',
 '509',
 '1327',
 '494',
 '1700',
 '15',
 '4',
 '4',
 '27',
 '750',
 '11',
 '1130',
 '11',
 '46',
 '20',
 '632',
 '632',
 '2195',
 '34',
 '1995',
 '48',
 '939',
 '632',
 '52',
 '187',
 '46',
 '6',
 '531',
 '74',
 '5500',
 '204',
 '610',
 '9',
 '374',
 '5000',
 '366',
 '1951',
 '610',
 '21',
 '915',
 '447',
 '3400',
 '6',
 '1662',
 '51',
 '625',
 '84',
 '18',
 '2896',
 '807',
 '160',
 '860',
 '1300',
 '1365',
 '350',
 '6',
 '2199',
 '3',
 '762',
 '11',
 '376',
 '147',
 '1905',
 '5',
 '7',
 '463',
 '1365',
 '155',
 '2300',
 '400',
 '397',
 '4',
 '95',
 '594',
 '157',
 '287',
 '5974',
 '3505',
 '1023',
 '244',
 '561',
 '183',
 '185',
 '1530',
 '78',
 '732',
 '258',
 '1067',
 '37',
 '2743',
 '240',
 '119',
 '1524',
 '211',
 '228',
 '343',
 '2000',
 '2438',
 '19',
 '10',
 '1',
 '1265',
 '26',
 '298',
 '299',
 '14',
 '320',
 '1993',
 '132',
 '2226',
 '171',
 '921',
 '2808',
 '95',
 '57',
 '468',
 '185',
 '155',
 '547',
 '180',
 '413',
 '185',
 '1260',
 '48',
 '625',
 '335',
 '7',
 '7',
 '43',
 '217',
 '2014',
 '183',
 '1288',
 '1463',
 '183',
 '2',
 '2200',
 '4335',
 '313',
 '80',
 '1524',
 '10',
 '99',
 '30',
 '238',
 '5430',
 '9',
 '506',
 '3500',
 '99',
 '763',
 '38',
 '38',
 '1220',
 '2100',
 '241',
 '3021',
 '4',
 '1006',
 '1768',
 '374',
 '695',
 '799',
 '7',
 '192',
 '495',
 '3087',
 '4',
 '3505',
 '15',
 '237',
 '2225',
 '1554',
 '346',
 '550',
 '326',
 '238',
 '3749',
 '92',
 '3',
 '244',
 '5',
 '540',
 '1494',
 '732',
 '237',
 '-3',
 '1200',
 '152',
 '228',
 '8',
 '1377',
 '457',
 '313',
 '1851',
 '686',
 '1800',
 '4420',
 '1463',
 '65',
 '2',
 '1533',
 '2712',
 '724',
 '430',
 '2443',
 '23',
 '907',
 '150',
 '197',
 '234',
 '2178',
 '701',
 '1325',
 '5',
 '201',
 '2',
 '132',
 '12',
 '500',
 '900',
 '3030',
 '228',
 '1006',
 '1886',
 '382',
 '33',
 '632',
 '143',
 '2559',
 '3054',
 '82',
 '2321',
 '5547',
 '2813',
 '270',
 '90',
 '2469',
 '80',
 '2301',
 '5',
 '1400',
 '762',
 '237',
 '152',
 '396',
 '1890',
 '1450',
 '320',
 '406',
 '1336',
 '248',
 '2406',
 '393',
 '108',
 '26',
 '367',
 '515',
 '1158',
 '4481',
 '2773',
 '2938',
 '25',
 '192',
 '298',
 '625',
 '228',
 '1377',
 '1716',
 '1402',
 '1189',
 '4877',
 '1030',
 '1830',
 '104',
 '6',
 '1059',
 '2767',
 '2560',
 '756',
 '701',
 '731',
 '809',
 '3368',
 '1189',
 '173',
 '35',
 '2120',
 '27',
 '11',
 '585',
 '494',
 '298',
 '49',
 '342',
 '209',
 '107',
 '238',
 '500',
 '567',
 '33',
 '802',
 '4',
 '1814',
 '207',
 '1551',
 '25',
 '3610',
 '384',
 '681',
 '1208',
 '843',
 '865',
 '4100',
 '1550',
 '975',
 '122',
 '1551',
 '384',
 '17',
 '349',
 '610',
 '3993',
 '3048',
 '153',
 '72',
 '1493',
 '2859',
 '1200',
 '1655',
 '2767',
 '1000',
 '1707',
 '2941',
 '43',
 '2926',
 '2834',
 '1760',
 '1687',
 '4',
 17003,
 '3',
 '997',
 '31',
 '80',
 '4100',
 '103',
 '625',
 '246',
 '275',
 '6',
 '2743',
 '8',
 '179',
 '61',
 '945',
 '753',
 '153',
 '1650',
 '18',
 '313',
 '4',
 '293',
 '432',
 '29',
 '121',
 '2774',
 '1703',
 '1541',
 '892',
 '2014',
 '685',
 '373',
 '1860',
 '62',
 '424',
 '911',
 '2916',
 '320',
 '19',
 '192',
 '1707',
 '1274',
 '34',
 '209',
 '3960',
 '241',
 '610',
 '1492',
 '4',
 '34',
 '142',
 '41',
 '126',
 '2384',
 '2192',
 '1981',
 '41',
 '488',
 '900',
 '488',
 '2530',
 '2357',
 '2064',
 '1890',
 '722',
 '3347',
 '760',
 9707,
 '700',
 '-',
 '1036',
 '3962',
 '2600',
 '1750',
 36628,
 '2160',
 '912',
 '400',
 '2682',
 '2900',
 '3980',
 '2286',
 '3901',
 '3645',
 '2540',
 '3660',
 '4115',
 '1048',
 '668']

In [4]:
showcols(df)
da = df.drop(df.columns[[2,30,31,14,15,27,2,14,26,24]],axis = 1, inplace = False) # Drop unnecessary columns
da = da.drop(da.columns[[2]],axis = 1, inplace = False) # Drop report status
showcols(da)
da.columns
da.groupby('Nature:').count()['id'] #Check groupby Nature for each

(0, 'year')
(1, 'id')
(2, 'url')
(3, 'Status:')
(4, 'Date:')
(5, 'Type:')
(6, 'Operator:')
(7, 'Registration:')
(8, 'C/n / msn:')
(9, 'First flight:')
(10, 'Engines:')
(11, 'Crew:')
(12, 'Passengers:')
(13, 'Total:')
(14, 'Aircraft damage:')
(15, 'Aircraft fate:')
(16, 'Location:')
(17, 'Phase:')
(18, 'Nature:')
(19, 'Departure airport:')
(20, 'Destination airport:')
(21, 'Narrative')
(22, 'Time:')
(23, 'Collision casualties:')
(24, 'Total airframe hrs:')
(25, 'Ground casualties:')
(26, 'Flightnumber:')
(27, 'Cycles:')
(28, 'Crash site elevation:')
(29, 'Operating for:')
(30, 'Leased from:')
(31, 'On behalf of:')
(32, 'Operated by:')
(0, 'year')
(1, 'id')
(2, 'Date:')
(3, 'Type:')
(4, 'Operator:')
(5, 'Registration:')
(6, 'C/n / msn:')
(7, 'First flight:')
(8, 'Engines:')
(9, 'Crew:')
(10, 'Passengers:')
(11, 'Total:')
(12, 'Location:')
(13, 'Phase:')
(14, 'Nature:')
(15, 'Departure airport:')
(16, 'Destination airport:')
(17, 'Narrative')
(18, 'Time:')
(19, 'Collision casualties:')
(20, 'Ground casualties:')
(21, 'Crash site elevation:')
(22, 'Operating for:')
(23, 'Operated by:')

Nature:
-                                     809
Aerial Work (Calibration, Photo)       23
Agricultural                          168
Ambulance                              92
Approach (APR)                          1
Cargo                                2007
Demonstration                          49
Domestic Non Scheduled Passenger      795
Domestic Scheduled Passenger         3850
Executive                             471
Ferry/positioning                     651
Fire fighting                          87
Illegal Flight                        201
Int'l Non Scheduled Passenger         324
International Scheduled Passenger    1367
Military                             8033
Non Scheduled Passenger                42
Official state flight                  41
Parachuting                            76
Passenger                             273
Private                               204
Scheduled Passenger                   142
Survey/research                       106
Test                                  230
Training                              421
Unknown                              2219
Unknown (UNK)                           2
Name: id, dtype: int64

In [5]:
import matplotlib.pyplot as plt
x = []
for i in k:
    try:
        x.append(int(i))
    except:
        x.append(-99999)
print(len(x))
#da['Elevations'] = x
#c = [i for i in da['Elevations'] if i !=None]
#plt.title('Elevation Distribution')
#plt.xlabel('Index')
#plt.ylabel('Elevation/FT',rotation =90)
#plt.plot(c)

601

In [6]:
da.rename(columns = lambda x:x.replace(':',''), inplace = True)
#showcols(da)
#da.groupby('Nature').count()['id']
da.loc[da['Nature']=='Unknown (UNK)','Nature'] = 'Unknown'
#Unknown merged.
da.drop(da[da['Phase'] == 'Standing (STD)'].index, inplace = True) # Stationary Data were dropped
da.drop(da[da['Phase'] == 'Unknown (UNK)'].index, inplace = True)
da.reset_index()

,index,year,id,Date,Type,Operator,Registration,C/n / msn,First flight,Engines,...,Nature,Departure airport,Destination airport,Narrative,Time,Collision casualties,Ground casualties,Crash site elevation,Operating for,Operated by
0,0,1919,1-02-AUG-1919,Saturday 2 August 1919,Caproni Ca.48,Caproni,registration unknown,NaN,1919,3 Liberty L-12,...,Passenger,"Venice-Marco Polo Airport (VCE/LIPZ), Italy","Milano-Taliedo Airport, Italy",The Caproni Ca.48 took off from the company's ...,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1919,2-11-AUG-1919,Monday 11 August 1919,Felixstowe Fury,Royal Air Force - RAF,N123,NaN,1918-11-11 (9 months),5 Rolls-Royce Eagle VIII,...,Test,"Felixstowe RNAS, United Kingdom","Felixstowe RNAS, United Kingdom",The Felixstowe Fury was test flown off Felixst...,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1920,1-23-FEB-1920,Monday 23 February 1920,Handley Page O/7,Handley Page Transport,G-EANV,HP-7,1919,NaN,...,Domestic Scheduled Passenger,?,?,Damaged beyond repair in a forced landing when...,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1920,3-30-JUN-1920,Wednesday 30 June 1920,Handley Page O/400,Handley Page Transport,G-EAKE,HP-22,1919,NaN,...,Demonstration,"Stockholm (unknown airport), Sweden","Kjeller Air Base (ENKJ), Norway",The Handley Page O/400 transport plane partici...,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1920,4-14-DEC-1920,Tuesday 14 December 1920,Handley Page O/400,Handley Page Transport,G-EAMA,HP-25,NaN,NaN,...,International Scheduled Passenger,"London-Cricklewood Aerodrome, United Kingdom","Paris-Le Bourget Airport (LBG/LFPB), France","A Handley Page O/400, operated by Handley Page...",ca 12:15,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16495,22793,2020,44-17-MAR-2020,Tuesday 17 March 2020,Cessna 208B Super Cargomaster,Planemasters,N274PM,208B0705,1998,1 Pratt & Whitney Canada PT6A-114A,...,Cargo,"Wichita Dwight D. Eisenhower National Airport,...","Hays Municipal Airport, KS (HYS/KHYS), United ...",A Planemaster Ltd Cessna 208B Super Cargomaste...,09:30:00,NaN,NaN,NaN,NaN,NaN
16496,22794,2020,45-19-MAR-2020,Thursday 19 March 2020,Cessna 208 Caravan I,Mission Aviation Fellowship - MAF,P2-MAF,20800198,1990,1 Pratt & Whitney Canada PT6A-114,...,Domestic Non Scheduled Passenger,"Kompiam Airport (KPM/AYAQ), Papua New Guinea","Yenkisa Airstrip (YEQ), Papua New Guinea",The MAF plane suffered a runway excursion on l...,ca 13:00,NaN,NaN,NaN,NaN,NaN
16497,22795,2020,46-22-MAR-2020,Sunday 22 March 2020,Hawker Siddeley HS-125-F400B,private,(XB-PNK),25227,1970,NaN,...,Illegal Flight,?,?,An abandoned corporate jet with running engine...,NaN,NaN,NaN,NaN,NaN,NaN
16498,22796,2020,47-29-MAR-2020,Sunday 29 March 2020,IAI 1124A Westwind II,Lionair Inc.,RP-C5880,353,1981,NaN,...,Ambulance,Manila-Ninoy Aquino International Airport (MNL...,"Tokyo-Haneda Airport (HND/RJTT), Japan",The IAI 1124A Westwind crashed on takeoff from...,ca 20:00,NaN,NaN,NaN,NaN,NaN
16499,22797,2020,48-05-APR-2020,Sunday 5 April 2020,Antonov An-26,Libyan National Army,registration unknown,NaN,NaN,NaN,...,Military,?,?,Antonov An-26 transport plane was destroyed in...,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
### Crew Cleaning
#showcols(da)
da.groupby('Crew').count()['id']
da.drop(da[da['Crew'] == 'Fatalities:  / Occupants:'].index,inplace = True) # Drop unrecorded columns
da.groupby('Crew').count()['id']
showcols(da)
da.drop(da.columns[[6,7,8,20,22,23]],axis = 1, inplace=True)

(0, 'year')
(1, 'id')
(2, 'Date')
(3, 'Type')
(4, 'Operator')
(5, 'Registration')
(6, 'C/n / msn')
(7, 'First flight')
(8, 'Engines')
(9, 'Crew')
(10, 'Passengers')
(11, 'Total')
(12, 'Location')
(13, 'Phase')
(14, 'Nature')
(15, 'Departure airport')
(16, 'Destination airport')
(17, 'Narrative')
(18, 'Time')
(19, 'Collision casualties')
(20, 'Ground casualties')
(21, 'Crash site elevation')
(22, 'Operating for')
(23, 'Operated by')

In [8]:
'''Dropped plane Types which are nulls.'''
showcols(da)
da.drop(da[da['Type'].isnull()].index, inplace = True)
#da[da['Type'].str.contains('Boeing',case = False)].groupby('Type').count()['id'].nlargest(25)

(0, 'year')
(1, 'id')
(2, 'Date')
(3, 'Type')
(4, 'Operator')
(5, 'Registration')
(6, 'Crew')
(7, 'Passengers')
(8, 'Total')
(9, 'Location')
(10, 'Phase')
(11, 'Nature')
(12, 'Departure airport')
(13, 'Destination airport')
(14, 'Narrative')
(15, 'Time')
(16, 'Collision casualties')
(17, 'Crash site elevation')

In [9]:
#Date formatting
da.drop(da[da['Date'].str.contains('xx',case = False)].index,inplace = True)
da['Raw_Time'] = da['Date'].apply(lambda x:time.strptime(x,"%A %d %B %Y"))
da['Raw_Time'].head(5)
da.reset_index()

,index,year,id,Date,Type,Operator,Registration,Crew,Passengers,Total,Location,Phase,Nature,Departure airport,Destination airport,Narrative,Time,Collision casualties,Crash site elevation,Raw_Time
0,0,1919,1-02-AUG-1919,Saturday 2 August 1919,Caproni Ca.48,Caproni,registration unknown,Fatalities: 2 / Occupants: 2,Fatalities: 12 / Occupants: 12,Fatalities: 14 / Occupants: 14,Verona ( Italy),En route (ENR),Passenger,"Venice-Marco Polo Airport (VCE/LIPZ), Italy","Milano-Taliedo Airport, Italy",The Caproni Ca.48 took off from the company's ...,NaN,NaN,NaN,"(1919, 8, 2, 0, 0, 0, 5, 214, -1)"
1,1,1919,2-11-AUG-1919,Monday 11 August 1919,Felixstowe Fury,Royal Air Force - RAF,N123,Fatalities: 1 / Occupants: 7,Fatalities: 0 / Occupants: 0,Fatalities: 1 / Occupants: 7,off Felixtowe RNAS ( United Kingdom),Initial climb (ICL),Test,"Felixstowe RNAS, United Kingdom","Felixstowe RNAS, United Kingdom",The Felixstowe Fury was test flown off Felixst...,NaN,NaN,NaN,"(1919, 8, 11, 0, 0, 0, 0, 223, -1)"
2,2,1920,1-23-FEB-1920,Monday 23 February 1920,Handley Page O/7,Handley Page Transport,G-EANV,Fatalities: 0 / Occupants:,Fatalities: 0 / Occupants:,Fatalities: 0 / Occupants: 10,"Acadia Siding, Cape Province ( South Africa)",En route (ENR),Domestic Scheduled Passenger,?,?,Damaged beyond repair in a forced landing when...,NaN,NaN,NaN,"(1920, 2, 23, 0, 0, 0, 0, 54, -1)"
3,4,1920,3-30-JUN-1920,Wednesday 30 June 1920,Handley Page O/400,Handley Page Transport,G-EAKE,Fatalities: 0 / Occupants: 2,Fatalities: 0 / Occupants: 0,Fatalities: 0 / Occupants: 2,Östanå ( Sweden),En route (ENR),Demonstration,"Stockholm (unknown airport), Sweden","Kjeller Air Base (ENKJ), Norway",The Handley Page O/400 transport plane partici...,NaN,NaN,NaN,"(1920, 6, 30, 0, 0, 0, 2, 182, -1)"
4,5,1920,4-14-DEC-1920,Tuesday 14 December 1920,Handley Page O/400,Handley Page Transport,G-EAMA,Fatalities: 2 / Occupants: 2,Fatalities: 2 / Occupants: 6,Fatalities: 4 / Occupants: 8,Golders Green ( United Kingdom),Initial climb (ICL),International Scheduled Passenger,"London-Cricklewood Aerodrome, United Kingdom","Paris-Le Bourget Airport (LBG/LFPB), France","A Handley Page O/400, operated by Handley Page...",ca 12:15,NaN,NaN,"(1920, 12, 14, 0, 0, 0, 1, 349, -1)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14572,22792,2020,43-14-MAR-2020,Saturday 14 March 2020,Raytheon Hawker 800XP,private,N100AG,Fatalities: 0 / Occupants: 2,Fatalities: 0 / Occupants: 0,Fatalities: 0 / Occupants: 2,"Phoenix-Scottsdale Municipal Airport, AZ (SCF)...",Landing (LDG),Private,"Rogers Municipal Airport-Carter Field, AR (ROG...","Phoenix-Scottsdale Municipal Airport, AZ (SCF/...","The Hawker 800XP, N100AG, was substantially da...",15:58:00,NaN,NaN,"(2020, 3, 14, 0, 0, 0, 5, 74, -1)"
14573,22793,2020,44-17-MAR-2020,Tuesday 17 March 2020,Cessna 208B Super Cargomaster,Planemasters,N274PM,Fatalities: 1 / Occupants: 1,Fatalities: 0 / Occupants: 0,Fatalities: 1 / Occupants: 1,"NW of La Crosse, Rush County, KS ( United St...",En route (ENR),Cargo,"Wichita Dwight D. Eisenhower National Airport,...","Hays Municipal Airport, KS (HYS/KHYS), United ...",A Planemaster Ltd Cessna 208B Super Cargomaste...,09:30:00,NaN,NaN,"(2020, 3, 17, 0, 0, 0, 1, 77, -1)"
14574,22794,2020,45-19-MAR-2020,Thursday 19 March 2020,Cessna 208 Caravan I,Mission Aviation Fellowship - MAF,P2-MAF,Fatalities: 0 / Occupants: 1,Fatalities: 0 / Occupants: 3,Fatalities: 0 / Occupants: 4,Yenkisa Airstrip (YEQ) ( Papua New Guinea),Landing (LDG),Domestic Non Scheduled Passenger,"Kompiam Airport (KPM/AYAQ), Papua New Guinea","Yenkisa Airstrip (YEQ), Papua New Guinea",The MAF plane suffered a runway excursion on l...,ca 13:00,NaN,NaN,"(2020, 3, 19, 0, 0, 0, 3, 79, -1)"
14575,22795,2020,46-22-MAR-2020,Sunday 22 March 2020,Hawker Siddeley HS-125-F400B,private,(XB-PNK),Fatalities: 0 / Occupants:,Fatalities: 0 / Occupants:,Fatalities: 0 / Occupants:,"near Caballo Blanco, Retalhuleu ( Guatemala)",Landing (LDG),Illegal Flight,?,?,An abandoned corporate jet with running engine...,NaN,NaN,NaN,"(2020, 3, 22, 0, 0, 0, 6, 82, -1)"
14576,22796,2020,47-29-MAR-2020,Sunday 29 March 2020,IAI 1124A Westwind II,Lionair Inc.,RP-C5880,Fatalities: 2 / Occupants: 2,Fatalities: 6 / Occupants: 6,Fatalities: 8 / Occupants: 8,Manila-Ninoy Aquino International Airport (MNL...,Takeoff (TOF),Ambulance,Manila-Ninoy Aquino International Airport (MNL...,"Tokyo-Haneda Airport (HND/RJTT), Japan",The IAI 1124A Westwind crashed on takeoff from...,ca 20:00,NaN,NaN,"(2020, 3, 29, 0, 0, 0, 6, 89, -1)"

In [16]:
da['Elevations'] = [None for i in range(len(da['Total_Fatality']))]
showcols(da)
da.head(3)
da.reset_index()
da['Total_Fatality'] = [get_occupants(i)[0] for i in da['Total']]
da['Total_Occupants'] = [get_occupants(i)[1] for i in da['Total']]
da['Fatality_Rate'] = da['Total_Fatality']/da['Total_Occupants']
da['Fatality_Rate'].describe()
da.drop(da[da['Fatality_Rate']>1].index,inplace = True)
da['Fatality_Rate'].describe()
da[da['Fatality_Rate'] ==max(da['Fatality_Rate'])]

(0, 'year')
(1, 'id')
(2, 'Date')
(3, 'Type')
(4, 'Operator')
(5, 'Registration')
(6, 'Crew')
(7, 'Passengers')
(8, 'Total')
(9, 'Location')
(10, 'Phase')
(11, 'Nature')
(12, 'Departure airport')
(13, 'Destination airport')
(14, 'Narrative')
(15, 'Time')
(16, 'Collision casualties')
(17, 'Crash site elevation')
(18, 'Raw_Time')
(19, 'Total_Fatality')
(20, 'Total_Occupants')
(21, 'Fatality_Rate')
(22, 'Make')
(23, 'Elevations')

,year,id,Date,Type,Operator,Registration,Crew,Passengers,Total,Location,...,Narrative,Time,Collision casualties,Crash site elevation,Raw_Time,Total_Fatality,Total_Occupants,Fatality_Rate,Make,Elevations
0,1919,1-02-AUG-1919,Saturday 2 August 1919,Caproni,Caproni,registration unknown,Fatalities: 2 / Occupants: 2,Fatalities: 12 / Occupants: 12,Fatalities: 14 / Occupants: 14,Verona ( Italy),...,The Caproni Ca.48 took off from the company's ...,NaN,NaN,NaN,"(1919, 8, 2, 0, 0, 0, 5, 214, -1)",14,14,1.0,ca.48,None
9,1921,4-26-AUG-1921,Friday 26 August 1921,Farman,SNETA - Syndicat National d'Etude du Transport...,O-BLAN,Fatalities: 2 / Occupants: 2,Fatalities: 0 / Occupants: 0,Fatalities: 2 / Occupants: 2,"5,6 km (3.5 mls) off Calais [The English Chan...",...,"A Farman F.60 Goliath, operating a mail fligh...",13:32:00,NaN,NaN,"(1921, 8, 26, 0, 0, 0, 4, 238, -1)",2,2,1.0,f.60 goliath,None
15,1922,3-07-APR-1922,Friday 7 April 1922,Farman,CGEA - Compagnie des Grands Express Aériens,F-GEAD,Fatalities: 2 / Occupants: 2,Fatalities: 3 / Occupants: 3,Fatalities: 5 / Occupants: 5,Thieuloy-Saint-Antoine ( France),...,"A Farman F.60 Goliath passenger plane, operate...",ca 14:00,Fatalities: 2,NaN,"(1922, 4, 7, 0, 0, 0, 4, 97, -1)",5,5,1.0,f.60 goliath,None
17,1923,2-14-MAY-1923,Monday 14 May 1923,Farman,Air Union (France),F-AEBY,Fatalities: 2 / Occupants: 2,Fatalities: 4 / Occupants: 4,Fatalities: 6 / Occupants: 6,"Monsures, Somme ( France)",...,Crashed following an in-flight failure (loss) ...,13:43:00,NaN,NaN,"(1923, 5, 14, 0, 0, 0, 0, 134, -1)",6,6,1.0,f.60 goliath,None
33,1927,1-05-MAY-1927,Thursday 5 May 1927,Farman,SGTA - Société Générale des Transports Aériens,F-ADFN,Fatalities: 2 / Occupants: 2,Fatalities: 0 / Occupants: 0,Fatalities: 2 / Occupants: 2,Atlantic Ocean ( Atlantic Ocean),...,"Disappeared at sea. On June 18, 1927, Brazilia...",NaN,NaN,NaN,"(1927, 5, 5, 0, 0, 0, 3, 125, -1)",2,2,1.0,f.61 goliath,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22771,2020,22-08-FEB-2020,Saturday 8 February 2020,Cessna,Remonia Air,N501RG,Fatalities: 2 / Occupants: 2,Fatalities: 2 / Occupants: 2,Fatalities: 4 / Occupants: 4,"near Fairmount, GA ( United States of America)",...,"The Cessna 501, N501RG, was destroyed after an...",10:13:00,NaN,NaN,"(2020, 2, 8, 0, 0, 0, 5, 39, -1)",4,4,1.0,501 citation i/sp,None
22777,2020,28-20-FEB-2020,Thursday 20 February 2020,Beechcraft,"Lauren Engineers & Constructors, Inc.",N860J,Fatalities: 1 / Occupants: 1,Fatalities: 2 / Occupants: 2,Fatalities: 3 / Occupants: 3,"near Lake Coleman, TX ( United States of Ame...",...,"A Beechcraft, B200 airplane, N860J, impacted t...",06:03:00,NaN,NaN,"(2020, 2, 20, 0, 0, 0, 3, 51, -1)",3,3,1.0,b200 king air,None
22791,2020,42-13-MAR-2020,Friday 13 March 2020,Cessna,Unknown,YV3452,Fatalities: 2 / Occupants: 2,Fatalities: 0 / Occupants: 0,Fatalities: 2 / Occupants: 2,Porlamar-del Caribe Santiago Mariño Internatio...,...,A Cessna 525 CitationJet suffered a runway exc...,18:10:00,NaN,NaN,"(2020, 3, 13, 0, 0, 0, 4, 73, -1)",2,2,1.0,525 citationjet,None
22793,2020,44-17-MAR-2020,Tuesday 17 March 2020,Cessna,Planemasters,N274PM,Fatalities: 1 / Occupants: 1,Fatalities: 0 / Occupants: 0,Fatalities: 1 / Occupants: 1,"NW of La Crosse, Rush County, KS ( United St...",...,A Planemaster Ltd Cessna 208B Super Cargomaste...,09:30:00,NaN,NaN,"(2020, 3, 17, 0, 0, 0, 1, 77, -1)",1,1,1.0,208b super cargomaster,None
22796,2020,47-29-MAR-2020,Sunday 29 March 2020,Iai,Lionair Inc.,RP-C5880,Fatalities: 2 / Occupants: 2,Fatalities: 6 / Occupants: 6,Fatalities: 8 / Occupants: 8,Manila-Ninoy Aquino International Airport (MNL...,...,The IAI 1124A Westwind crashed on takeoff from...,ca 20:00,NaN,NaN,"(2020, 3, 29, 0, 0, 0, 6, 89, -1)",8,8,1.0,1124a westwind ii,None

In [11]:
#Group by make and types
da['Type'] = da['Type'].apply(lambda x:x.capitalize())
da['Type']
da['Make'] = da['Type'].apply(lambda x:' '.join(x.split()[1:]))
da['Type'] = da['Type'].apply(lambda x:x.split()[0])
da.groupby('Type').mean()['Fatality_Rate'].nsmallest(50)

Type
Antononv               0.000000
Beriev                 0.000000
Bushmaster             0.000000
Excel-jet              0.000000
Fma                    0.000000
Honda                  0.000000
Lyushin                0.000000
Mcdonnell-douglas      0.000000
Northrop               0.000000
Oakland                0.000000
Padc/britten-norman    0.000000
Saunders               0.000000
Shinmaywa              0.000000
Sud-aviation           0.002551
Bombardier             0.066667
Mohawk                 0.080000
Airbus                 0.131483
Felixstowe             0.142857
Naval                  0.150000
Unknown                0.153846
Xian                   0.153846
Airspeed               0.159091
Raytheon               0.166667
Steward-davis          0.166667
Saab                   0.168129
Mitusbishi             0.181818
Armstrong              0.190476
Budd                   0.197917
Basler                 0.200000
Eclipse                0.200000
Mcdonnell              0.204375
Bac                    0.211347
Atr                    0.215644
Namc                   0.224029
Scottish               0.238095
Sncase                 0.248352
Swearingen             0.249921
Hal/dornier            0.250000
Padc/pilatus           0.250000
Boeing                 0.250421
Casa/iptn              0.261905
Blériot                0.266667
Dassault               0.282889
Dornier                0.287357
Vought-sikorsky        0.297297
Sukhoi                 0.305128
Hawker                 0.308142
Gulfstream             0.311111
Fokker                 0.311176
British                0.317259
Name: Fatality_Rate, dtype: float64

In [21]:
da[da['Type'].str.contains('North')]['Make']
da.head(2)
da.to_csv('testflight.csv',index = False)
print(da.tail(1))

       year              id                  Date Type      Operator  \
22796  2020  47-29-MAR-2020  Sunday 29 March 2020  Iai  Lionair Inc.

      Registration                          Crew  \
22796     RP-C5880  Fatalities: 2 / Occupants: 2

                         Passengers                         Total  \
22796  Fatalities: 6 / Occupants: 6  Fatalities: 8 / Occupants: 8

                                                Location  ...  \
22796  Manila-Ninoy Aquino International Airport (MNL...  ...

                                               Narrative      Time  \
22796  The IAI 1124A Westwind crashed on takeoff from...  ca 20:00

      Collision casualties Crash site elevation  \
22796                  NaN                  NaN

                                Raw_Time Total_Fatality Total_Occupants  \
22796  (2020, 3, 29, 0, 0, 0, 6, 89, -1)              8               8

      Fatality_Rate               Make  Elevations
22796           1.0  1124a westwind ii        None

[1 rows x 24 columns]

In [13]:
showcols(da)
da['Location']
da.to_csv(path_or_buf='../data/cleanedbig.csv')

(0, 'year')
(1, 'id')
(2, 'Date')
(3, 'Type')
(4, 'Operator')
(5, 'Registration')
(6, 'Crew')
(7, 'Passengers')
(8, 'Total')
(9, 'Location')
(10, 'Phase')
(11, 'Nature')
(12, 'Departure airport')
(13, 'Destination airport')
(14, 'Narrative')
(15, 'Time')
(16, 'Collision casualties')
(17, 'Crash site elevation')
(18, 'Raw_Time')
(19, 'Total_Fatality')
(20, 'Total_Occupants')
(21, 'Fatality_Rate')
(22, 'Make')

In [4]:
dt = pd.read_csv('cleanedsmall.csv')
pd.merge(da, dt, left_on=key_or_keys, right_index=True,
      how='left', sort=False)
pd.to_csv('cleaned_final.csv')